config/routes.rb
Rails.application.routes.draw do
  resources :jogos
  resources :pistas
  resources :pessoas
  get 'hello/index'
  get 'hello/usuario'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jogo.rb
class Jogo < ApplicationRecord
  belongs_to :pessoa
  belongs_to :pista
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/pista.rb
class Pista < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
       # render plain: "hello"
    end

    def usuario
        @usuario = Usuario.first
    end
    
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.all
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
  end

  # GET /jogos/1/edit
  def edit
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to @jogo, notice: 'Jogo was successfully created.' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'Jogo was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'Jogo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.require(:jogo).permit(:pessoa_id, :pista_id)
    end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :tipo, :matricula, :escola)
    end
end

app/controllers/pistas_controller.rb
class PistasController < ApplicationController
  before_action :set_pista, only: [:show, :edit, :update, :destroy]

  # GET /pistas
  # GET /pistas.json
  def index
    @pistas = Pista.all
  end

  # GET /pistas/1
  # GET /pistas/1.json
  def show
  end

  # GET /pistas/new
  def new
    @pista = Pista.new
  end

  # GET /pistas/1/edit
  def edit
  end

  # POST /pistas
  # POST /pistas.json
  def create
    @pista = Pista.new(pista_params)

    respond_to do |format|
      if @pista.save
        format.html { redirect_to @pista, notice: 'Pista was successfully created.' }
        format.json { render :show, status: :created, location: @pista }
      else
        format.html { render :new }
        format.json { render json: @pista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pistas/1
  # PATCH/PUT /pistas/1.json
  def update
    respond_to do |format|
      if @pista.update(pista_params)
        format.html { redirect_to @pista, notice: 'Pista was successfully updated.' }
        format.json { render :show, status: :ok, location: @pista }
      else
        format.html { render :edit }
        format.json { render json: @pista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pistas/1
  # DELETE /pistas/1.json
  def destroy
    @pista.destroy
    respond_to do |format|
      format.html { redirect_to pistas_url, notice: 'Pista was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pista
      @pista = Pista.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pista_params
      params.require(:pista).permit(:numero, :localizacao, :pontos)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/pistas_helper.rb
module PistasHelper
end

app/views/hello/index.html.erb
<h1>Hello</h1>

app/views/hello/usuario.html.erb
<h2>Olá <%= @usuario.nome %></h2>

app/views/jogos/_form.html.erb
<%= form_with(model: jogo, local: true) do |form| %>
  <% if jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% jogo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pessoa_id %>
    <%= form.text_field :pessoa_id %>
  </div>

  <div class="field">
    <%= form.label :pista_id %>
    <%= form.text_field :pista_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogos</h1>

<table>
  <thead>
    <tr>
      <th>Pessoa</th>
      <th>Pista</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= jogo.pessoa %></td>
        <td><%= jogo.pista %></td>
        <td><%= link_to 'Show', jogo %></td>
        <td><%= link_to 'Edit', edit_jogo_path(jogo) %></td>
        <td><%= link_to 'Destroy', jogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jogo', new_jogo_path %>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pessoa:</strong>
  <%= @jogo.pessoa %>
</p>

<p>
  <strong>Pista:</strong>
  <%= @jogo.pista %>
</p>

<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APPTeste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :escola %>
    <%= form.text_field :escola %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Matricula</th>
      <th>Escola</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.tipo %></td>
        <td><%= pessoa.matricula %></td>
        <td><%= pessoa.escola %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @pessoa.tipo %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @pessoa.matricula %>
</p>

<p>
  <strong>Escola:</strong>
  <%= @pessoa.escola %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/pistas/_form.html.erb
<%= form_with(model: pista, local: true) do |form| %>
  <% if pista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pista.errors.count, "error") %> prohibited this pista from being saved:</h2>

      <ul>
      <% pista.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :localizacao %>
    <%= form.text_field :localizacao %>
  </div>

  <div class="field">
    <%= form.label :pontos %>
    <%= form.text_field :pontos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pistas/edit.html.erb
<h1>Editing Pista</h1>

<%= render 'form', pista: @pista %>

<%= link_to 'Show', @pista %> |
<%= link_to 'Back', pistas_path %>

app/views/pistas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pistas</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Localizacao</th>
      <th>Pontos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pistas.each do |pista| %>
      <tr>
        <td><%= pista.numero %></td>
        <td><%= pista.localizacao %></td>
        <td><%= pista.pontos %></td>
        <td><%= link_to 'Show', pista %></td>
        <td><%= link_to 'Edit', edit_pista_path(pista) %></td>
        <td><%= link_to 'Destroy', pista, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pista', new_pista_path %>

app/views/pistas/new.html.erb
<h1>New Pista</h1>

<%= render 'form', pista: @pista %>

<%= link_to 'Back', pistas_path %>

app/views/pistas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @pista.numero %>
</p>

<p>
  <strong>Localizacao:</strong>
  <%= @pista.localizacao %>
</p>

<p>
  <strong>Pontos:</strong>
  <%= @pista.pontos %>
</p>

<%= link_to 'Edit', edit_pista_path(@pista) %> |
<%= link_to 'Back', pistas_path %>